### PR TITLE
fix assertion when breakpoint triggers during wrapper step through

### LINKED ISSUE #215: ERROR: AssertionError: is_leaf(frame)
I'm trying to run Debugger on Pkg using the usual trick of commenting out my dev Pkg's uuid in the project file and then loading that one as a new package and then running it in the debugger and I'm getting this error:
```jl
julia> @enter Pkg.resolve()
resolve() in Pkg.API at /Users/stefan/dev/Pkg/src/API.jl:172, pc = 1
  Pkg.Types.Context() in Pkg.Types at util.jl:723
    Pkg.Types.EnvCache() in Pkg.Types at /Users/stefan/dev/Pkg/src/Types.jl:314
      Pkg.Types.EnvCache(env::Union{Nothing, String}) in Pkg.Types at /Users/stefan/dev/Pkg/src/Types.jl:314
        find_project_file(env::Union{Nothing, String}) in Pkg.Types at /Users/stefan/dev/Pkg/src/Types.jl:207
          safe_realpath(path) in Pkg.Types at /Users/stefan/dev/Pkg/src/Types.jl:480
            realpath(path::AbstractString) in Base.Filesystem at path.jl:375
              getproperty(x::Module, f::Symbol) in Base at Base.jl:13
node = :(($(QuoteNode(Pkg.Types.Context)))())
ERROR: AssertionError: is_leaf(frame)
Stacktrace:
 [1] step_expr!(::Any, ::JuliaInterpreter.Frame, ::Any, ::Bool) at /Users/stefan/.julia/packages/JuliaInterpreter/8bMSs/src/interpret.jl:404
 [2] step_expr! at /Users/stefan/.julia/packages/JuliaInterpreter/8bMSs/src/interpret.jl:536 [inlined]
 [3] next_until!(::Any, ::Any, ::JuliaInterpreter.Frame, ::Bool) at /Users/stefan/.julia/packages/JuliaInterpreter/8bMSs/src/commands.jl:93
 [4] next_call! at /Users/stefan/.julia/packages/JuliaInterpreter/8bMSs/src/commands.jl:112 [inlined]
 [5] maybe_step_through_wrapper!(::Any, ::JuliaInterpreter.Frame) at /Users/stefan/.julia/packages/JuliaInterpreter/8bMSs/src/commands.jl:246
 [6] maybe_step_through_wrapper!(::JuliaInterpreter.Frame) at /Users/stefan/.julia/packages/JuliaInterpreter/8bMSs/src/commands.jl:256
 [7] top-level scope at /Users/stefan/.julia/packages/Debugger/JwW1u/src/Debugger.jl:90
```
I have also set a breakpoint, which seems to be necessary for this to be triggered. This is the breakpoint I set: `@breakpoint Pkg.Operations.resolve_versions!`.

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes #215

### CODE REVIEW

File: test/debug.jl [hunk 1]
```diff
@@ -425,6 +425,13 @@ struct B{T} end
         @test frame.pc == 1
     end
 
+    @testset "breakpoints hit during wrapper step through" begin
+        f(x = g()) = x
+        g() = 5
+        @breakpoint g()
+        frame = JuliaInterpreter.enter_call(f)
+        JuliaInterpreter.maybe_step_through_wrapper!(frame)
+        @test leaf(frame).framecode.scope == @which g()
```
Comment (timholy) [inline test/debug.jl]:
```suggestion
        @test leaf(frame).framecode.scope == @which g()
    end
```
