### PR TITLE
fixup for name change of #kw##invoke on 1.4

### LINKED ISSUE #344: `using Debugger` on Julia's master branch fails
I have just compiled Julia's master branch, installed `Debugger.jl` and tried to import it with `using Debugger`. Here is what I get:

```julia
julia on  master 
❯ ./julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.4.0-DEV.215 (2019-10-01)
 _/ |\__'_|_|_|\__'_|  |  Commit 2859b11a12 (0 days old master)
|__/                   |

julia> using Debugger
[ Info: Precompiling Debugger [31a5f54b-26ea-5ae9-a837-f05ce5417438]
ERROR: LoadError: LoadError: UndefVarError: #kw##invoke not defined
Stacktrace:
 [1] top-level scope at /home/alex/.julia/packages/JuliaInterpreter/Up48R/src/builtins.jl:13
 [2] include(::Module, ::String) at ./Base.jl:377
 [3] include(::String) at /home/alex/.julia/packages/JuliaInterpreter/Up48R/src/JuliaInterpreter.jl:1
 [4] top-level scope at /home/alex/.julia/packages/JuliaInterpreter/Up48R/src/JuliaInterpreter.jl:42
 [5] include(::Module, ::String) at ./Base.jl:377
 [6] top-level scope at none:2
 [7] eval at ./boot.jl:330 [inlined]
 [8] eval(::Expr) at ./client.jl:458
 [9] top-level scope at ./none:3
in expression starting at /home/alex/.julia/packages/JuliaInterpreter/Up48R/src/builtins.jl:13
in expression starting at /home/alex/.julia/packages/JuliaInterpreter/Up48R/src/JuliaInterpreter.jl:42
ERROR: LoadError: Failed to precompile JuliaInterpreter [aa1ae85d-cabe-5617-a682-6adf51b2e16a] to /home/alex/.julia/compiled/v1.4/JuliaInterpreter/PliIn_OlkWB.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1262
 [3] _require(::Base.PkgId) at ./loading.jl:1024
 [4] require(::Base.PkgId) at ./loading.jl:922
 [5] require(::Module, ::Symbol) at ./loading.jl:917
 [6] include(::Module, ::String) at ./Base.jl:377
 [7] top-level scope at none:2
 [8] eval at ./boot.jl:330 [inlined]
 [9] eval(::Expr) at ./client.jl:458
 [10] top-level scope at ./none:3
in expression starting at /home/alex/.julia/packages/Debugger/XqeyI/src/Debugger.jl:14
ERROR: Failed to precompile Debugger [31a5f54b-26ea-5ae9-a837-f05ce5417438] to /home/alex/.julia/compiled/v1.4/Debugger/UDHul_OlkWB.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1262
 [3] _require(::Base.PkgId) at ./loading.jl:1024
 [4] require(::Base.PkgId) at ./loading.jl:922
 [5] require(::Module, ::Symbol) at ./loading.jl:917
```

Any ideas why this happens?

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes #344 

~~We still have some test failures on master:~~

```
Keyword arguments: Error During Test at /home/kc/JuliaPkgs/JuliaInterpreter.jl/test/debug.jl:179
  Test threw exception
  Expression: get_return(frame) == 6
  expected return statement, got (SSAValue(15))(SSAValue(16), JuliaInterpreter.SlotNumber(3), JuliaInterpreter.SlotNumber(4))
  Stacktrace:
   [1] error(::String, ::Expr) at ./error.jl:42
   [2] get_return(::Frame) at /home/kc/JuliaPkgs/JuliaInterpreter.jl/src/interpret.jl:609
   [3] top-level scope at /home/kc/JuliaPkgs/JuliaInterpreter.jl/test/debug.jl:179
   [4] top-level scope at /home/kc/julia/usr/share/julia/stdlib/v1.4/Test/src/Test.jl:1108
   [5] top-level scope at /home/kc/JuliaPkgs/JuliaInterpreter.jl/test/debug.jl:163

Stepping over kwfunc preparation: Test Failed at /home/kc/JuliaPkgs/JuliaInterpreter.jl/test/debug.jl:406
  Expression: frame.pc > 4
   Evaluated: 2 > 4
Stacktrace:
 [1] top-level scope at /home/kc/JuliaPkgs/JuliaInterpreter.jl/test/debug.jl:406
 [2] top-level scope at /home/kc/julia/usr/share/julia/stdlib/v1.4/Test/src/Test.jl:1108
 [3] top-level scope at /home/kc/JuliaPkgs/JuliaInterpreter.jl/test/debug.jl:387
Stepping over kwfunc preparation: Test Failed at /home/kc/JuliaPkgs/JuliaInterpreter.jl/test/debug.jl:413
  Expression: frame.pc == JuliaInterpreter.nstatements(frame.framecode) - 1
   Evaluated: 2 == 10
Stacktrace:
 [1] top-level scope at /home/kc/JuliaPkgs/JuliaInterpreter.jl/test/debug.jl:413
 [2] top-level scope at /home/kc/julia/usr/share/julia/stdlib/v1.4/Test/src/Test.jl:1108
 [3] top-level scope at /home/kc/JuliaPkgs/JuliaInterpreter.jl/test/debug.jl:387
```

I think most of this is because our kw_prep stepper doesn't work correctly anymore.

### CODE REVIEW

**Comment by KristofferC** [comment]
Ok, fixed a few of them.

**Comment by KristofferC** [comment]
We have this extra dude now:

```
(Frame for f#3(b, ::typeof(f), x) in Main at REPL[3]:1
  1 1  1 ─      $(Expr(:meta, :nkw, 1)) # <------------------ hi there
  2 1  │   %2 = (+)(x, b)
  3 1  └──      return %2
```

**Comment by KristofferC** [comment]
Should pass now.

File: bin/generate_builtins.jl [hunk 1]
```diff
@@ -228,8 +233,8 @@ function maybe_evaluate_builtin(frame, call_expr, expand::Bool)
     print(io,
 """
     end
-    if isa(f, getfield(Core, Symbol("#kw##invoke")))
-        return Some{Any}(getfield(Core, Symbol("#kw##invoke"))(getargs(args, frame)...))
+    if isa(f, getfield(Core, kwinvoke_name))
```
Comment (pfitzseb) [inline bin/generate_builtins.jl]: `getfield(Core, kwinvoke_name)` -> `kwinvoke_instance`?

File: src/builtins.jl [hunk 2]
```diff
@@ -228,7 +229,7 @@ function maybe_evaluate_builtin(frame, call_expr, expand::Bool)
         cargs = getargs(args, frame)
         return Some{Any}(ccall(:jl_f_intrinsic_call, Any, (Any, Ptr{Any}, UInt32), f, cargs, length(cargs)))
     end
-    if isa(f, getfield(Core, Symbol("#kw##invoke")))
+    if isa(f, getfield(Core, kwinvoke_name))
```
Comment (pfitzseb) [inline src/builtins.jl]: `getfield(Core, kwinvoke_name)` -> `kwinvoke_instance`?

Comment (KristofferC) [reply src/builtins.jl]: Hm, I don't think so.

Comment (pfitzseb) [reply src/builtins.jl]: Oh, true, sorry. Doesn't matter much either way, it's not like a `getfield` is going to make a performance difference or anything.
