### PR TITLE
Interpret most of Core.Compiler

### LINKED ISSUE #242: Don't blanket ban `Core.Compiler` from interpretation
In https://github.com/JuliaDebug/Debugger.jl/issues/150 I wanted to use Debugger.jl to step through a method in `Core.Compiler`. This is currently blocked by https://github.com/JuliaDebug/JuliaInterpreter.jl/blob/6b93e041614b697ed0c05dc68075b863849095c2/src/construct.jl#L119-L121 

It would be awesome if I could use the Debugger for Core.Compiler, but I am okay with having this be a special case (similar to `Revise.track(Core.Compiler)`).

### LINKED ISSUE #257: The interpreter does not handle SSAValues that occur in code correctly
Edit: Updated to an even more minimum MWE...

We are handling SSAValues in code erroneously:

```jl
function f()
    z = [Core.SSAValue(5),]
    @show z[1]
end
```

```jl
julia> f();
z[1] = :(%5)

julia> @interpret f();
ERROR: UndefRefError: access to undefined reference
Stacktrace:
 [1] getindex at .\array.jl:729 [inlined]
 [2] lookup_var at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\interpret.jl:8 [inlined]
 [3] #collect_args#35(::Bool, ::Function, ::Frame, ::Expr) at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\interpret.jl:64
 [4] collect_args at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\interpret.jl:139 [inlined]
 [5] #evaluate_call_recurse!#39(::Bool, ::Function, ::Any, ::Frame, ::Expr) at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\interpret.jl:211
 [6] evaluate_call_recurse! at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\interpret.jl:205 [inlined]
 [7] eval_rhs(::Any, ::Frame, ::Expr) at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\interpret.jl:371
 [8] step_expr!(::Any, ::Frame, ::Any, ::Bool) at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\interpret.jl:504
```

### PR DESCRIPTION
**Pull request by timholy**
This opens most of `Core.Compiler` to the interpreter. The unfortunate exceptions are some of the most interesting functions, the various `typeinf_*` functions: so far I have been unable to avoid segfaults from anything that starts a `ccall(:jl_typeinf_begin, ...)` block. However, hopefully this is still a considerable improvement from where we are currently. (Thoughts, @vchuravy?)

There are three substantive changes:
- Avoid using `Core.SlotNumber` and `Core.SSAValue`. Instead, we define equivalent types here and replace the values that come by from `Base.uncompressed_ast` with the local equivalents. This allows us to distinguish an `SSAValue` generated as a value from `Core.Compiler` methods vs one that's being used by the interpreter. Disadvantage: I suspect frame printing is broken. That's one reason this is a WIP.
- `ccall`s made from `Core.Compiler` have to have their compiled variants evaluated in `Core.Compiler` rather than `JuliaInterpreter.CompiledCalls`. The reason is that `Core.Compiler.unsafe_convert != Base.unsafe_convert` and `Core.Compiler.cconvert != Base.cconvert` and these end up getting used by Julia internally when implementing our compiled variants.
- In a (failed) attempt to avoid those segfaults, I set up a mechanism to re-used previous compiled `ccall` functions. As a consequence one no longer needs one per call site, it's just one per type signature. This seems useful on its own, even if it didn't fix the core problem I was trying to solve.

Fixes #257. Fixes #242. Closes #258.

### CODE REVIEW

**Comment by KristofferC** [comment]
Pushed commits with test for SSAValue handling and fixup for the Frame printing.

File: src/JuliaInterpreter.jl [hunk 1]
```diff
@@ -70,12 +70,43 @@ function set_compiled_methods()
...
+    #                       (:jl_value_ptr, Ptr{Cvoid}, (Any,)))
+    #     fname = Symbol(:ccall_, sym)
+    #     qsym = QuoteNode(sym)
+    #     argnames = [Symbol(:arg_, string(i)) for i = 1:length(AT)]
+    #     TAT = Expr(:tuple, [parametric_type_to_expr(t) for t in AT]...)
+    #     def = :($fname($(argnames...)) = ccall($qsym, $RT, $TAT, $(argnames...)))
+    #     f = Core.eval(Core.Compiler, def)
+    #     compiled_calls[(qsym, RT, Core.svec(AT...), Core.Compiler)] = f
+    #     precompile(f, AT)
+    # end
```
Comment (timholy) [inline src/JuliaInterpreter.jl]: Should I strip this block out or leave it commented out? It's possible this is on the right track towards getting `typeinf_ext` and friends working (and simply not yet sufficient on its own), but it's also possible this is irrelevant.

Comment (KristofferC) [reply src/JuliaInterpreter.jl]: Not sure, doesn't matter to me so do as you wish.

**Comment by vchuravy** [comment]
Whoo! That is fabulous thank you guys!
