### PR TITLE
rejigger the code to compute the method instance in stacktraces

### LINKED ISSUE #562: Access to undefined reference Julia 1.9
I get a `UndefRefError: access to undefined reference` on this line: https://github.com/JuliaDebug/JuliaInterpreter.jl/blob/b2ebd69390efcfe37f50a7ab91ce1ee25457a2e0/src/utils.jl#L740 where I have
```
frame.framedata.sparams = Any[#undef, Int64, typeof(identity)]
```
I don't have a (small) reproducer.

### PR DESCRIPTION
**Pull request by KristofferC**
this works around a bug that occurs when there is an undefined sparams

Fixes #562

### CODE REVIEW

**Review by timholy — APPROVED** [review]

**Review by aviatesk — COMMENTED** [review]
Test failures on nightly are unrelated and going to be fixed by #564.

**Review by aviatesk — APPROVED** [review]

File: src/utils.jl [hunk 1]
```diff
@@ -735,10 +735,10 @@ function Base.StackTraces.StackFrame(frame::Frame)
     if scope isa Method
         method = scope
         method_args = [something(frame.framedata.locals[i]) for i in 1:method.nargs]
-        atypes = Tuple{mapany(_Typeof, method_args)...}
+        argt = Tuple{mapany(_Typeof, method_args)...}
         sig = method.sig
-        sparams = Core.svec(frame.framedata.sparams...)
-        mi = Core.Compiler.specialize_method(method, atypes, sparams)
+        atype, sparams = ccall(:jl_type_intersection_with_env, Any, (Any, Any), argt, sig)::SimpleVector
+        mi = Core.Compiler.specialize_method(method, atype, sparams)
```
Comment (aviatesk) [inline src/utils.jl:741]:
```suggestion
        mi = Core.Compiler.specialize_method(method, atype, sparams::SimpleVector)
```
