### PR TITLE
fix interpreting getting env vars on windows

### LINKED ISSUE #141: Divergence between compiler and interpreter with logging macros
```jl
julia> function f()
           x = 1 + 1
           @info "hello"
       end
f (generic function with 1 method)

julia> f()
[ Info: hello

julia> @interpret f()
Exception handling log message: ArgumentError("input string is empty or only contains whitespace")
  module=Main  file=REPL[3]  line=3
  Second exception: ArgumentError("input string is empty or only contains whitespace")
```

### PR DESCRIPTION
**Pull request by KristofferC**
We should probably enable AV heh.

Fixes #141

### CODE REVIEW

File: src/JuliaInterpreter.jl [hunk 1]
```diff
@@ -59,6 +59,11 @@ function set_compiled_methods()
...
     # Signal-handling in the `print` dispatch hierarchy
     push!(compiled_methods, which(Base.unsafe_write, Tuple{Base.LibuvStream, Ptr{UInt8}, UInt}))
+    # Libc.GetLastError()
+    @static if Sys.iswindows()
+        push!(compiled_methods, which(Base.access_env, Tuple{Function, AbstractString}))
+        push!(compiled_methods, which(Base._hasenv, Tuple{Vector{UInt16}}))
+    end
 end
 
 function __init__()
```
Comment (KristofferC) [inline src/JuliaInterpreter.jl]: Are methods not persistent between julia sessions? We really need this in `__init__()`?

Comment (timholy) [reply src/JuliaInterpreter.jl]: Not certain; if they are compared via pointer I wonder if you'd have to rehash.
